name: "Traversal Packages"
author: "xinxinxiangying258"
description: "Traversal all versions of kungfu-trader's packages"
//inputs这里还需要修改（）
inputs:
  token:
    description: "GitHub token"
  expire-in:
    required: true
    description: 'Human readable expire duration'
  only-prefix:
    required: false
    description: 'Only artifacts with the specified prefix will be deleted'
    default: ''
  except-prefix:
    required: false
    description: 'Artifacts with this prefix will not be included for deletion'
    default: ''
runs:
  using: "node12"
  main: "dist/index.js"
