name: "Traversal Packages"
author: "xinxinxiangying258"
description: "Traversal all versions of kungfu-trader's packages"
inputs:
  token:
    description: "Github token. E.g. secrets.GITHUB_TOKEN"
    required: true
  expire-in:
    required: true
    description: 'Human readable expire duration'
  action:
    description: "Choices [auto/prebuild/postbuild/verify]"
    default: "auto"
  no-publish:
    description: "Choices [true/false]"
    default: "false"
  no-protection:
    description: "Choices [true/false]"
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
